### ISSUE TITLE
Apple App Store Rejecting Application

### ISSUE THREAD

**Issue by Some1Somewhere** [Almoullim/background_location#102]
Have implemented background location service and it is working as well, as checked through test flight and in my simulator, The background data is being read and transmitted. However, it is still being rejected for publshing.  Please let me know if I can remove the location in UIBackgroundModes or if there is any other fix. 

> Guideline 2.5.4 - Performance - Software Requirements
> 
> 
> Your app declares support for location in the UIBackgroundModes key in your Info.plist file but does not have any features that require persistent location. Apps that declare support for location in the UIBackgroundModes key in your Info.plist file must have features that require persistent location.
> 
> Next Steps
> 
> To resolve this issue, please revise your app to include features that require the persistent use of real-time location updates while the app is in the background.
> 
> If your app does not require persistent real-time location updates, please remove the "location" setting from the UIBackgroundModes key. You may wish to use the significant-change location service or the region monitoring location service if persistent real-time location updates are not required for your app features.

**Comment by Ajay9o9** [comment]
Did you fix this issue, can you tell me how

**Comment by MoralCode** [comment]
I believe that this rule is referring to the features of your specific app that Apple either A) didn't see, or B) aren't convinced that it requires the use of background location. It seems like this rule is put in place to stop apps from using background location unnecessarily and is something that you should resolve with Apple.

I don't think this issue is related to the operation of this flutter plugin.
