### ISSUE TITLE
Could you please migrating the plugin to the V2 embedding

### ISSUE THREAD

**Issue by EdisonJwa** [Almoullim/background_location#113]
The plugin `background_location` uses a deprecated version of the Android embedding.
To avoid unexpected runtime failures, or future build failures, try to see if this plugin supports the Android V2 embedding. Otherwise, consider removing it since a future release of Flutter will remove these deprecated APIs.
If you are plugin author, take a look at the docs for migrating the plugin to the V2 embedding: https://flutter.dev/go/android-plugin-migration.

**Comment by ozz-rjq** [comment]
having the same issue

**Comment by chirag-chopra** [comment]
I am also facing the same issue... Please fix this at top priority

**Comment by lukaskurz** [comment]
Same issue here, although it's just a build warning. I would try to migrate it myself and send a PR, but I have no idea how to get AndroidStudio and it's intellisense/autocompletion running in the android folder :( if someone can help me with this, I can give the migration a try.

**Comment by khanems** [comment]
Same please fix issue

**Comment by Alecckie** [comment]
I am receiving the following 2 errors on RELEASE
1. The plugin `background_location` use a deprecated version of the Android embedding.
To avoid unexpected runtime failures, or future build failures, try to see if these plugins support the Android V2 embedding. Otherwise, consider removing them since a future
release of Flutter will remove these deprecated APIs.
2. AAPT: error: attribute android:foregroundService
Type not found

The plugin is perfect in debug mode but could they just update these to make it work in release mode kindly?

**Comment by nicks258** [comment]
Any Updates?

**Comment by lukaskurz** [comment]
Currently trying to change this to v2 embedding in a fork, but this is my first coding native stuff for flutter (also had to play around with the .idea files, since it did not want to load in android studio)
