### ISSUE TITLE
not working when app killed on Android

### ISSUE THREAD

**Issue by akabhinavv3** [Almoullim/background_location#194]
is it work when app is in killed state?

**Comment by MoralCode** [comment]
Can you provide more details about your setup and the steps you took to lead to this?

**Comment by akabhinavv3** [comment]
import 'package:flutter/material.dart';
import 'package:background_location/background_location.dart';

void main() => runApp(MyApp());

class MyApp extends StatefulWidget {
  @override
  _MyAppState createState() => _MyAppState();
}

class _MyAppState extends State<MyApp> {
  @override
  void initState() {
    super.initState();
    initBackgroundLocation();
  }

  void initBackgroundLocation() async {
    await BackgroundLocation.setAndroidNotification(
      title: 'Background service is running',
      message: 'Background location in progress',
      icon: '@mipmap/ic_launcher',
    );

    await BackgroundLocation.startLocationService(distanceFilter: 20);


    BackgroundLocation.setAndroidConfiguration(3); // Set the update interval to 300 seconds (5 minutes)

    BackgroundLocation.getLocationUpdates((location) {
      // Handle location updates here
      print('Location update: ${location.latitude}, ${location.longitude}');
    });

    // Start the location service explicitly when the app starts
    BackgroundLocation.startLocationService();
  }

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        appBar: AppBar(
          title: Text('Background Location Service'),
        ),
        body: Center(
          child: Text('App is running in the background fetching location...'),
        ),
      ),
    );
  }

  @override
  void dispose() {
    BackgroundLocation.stopLocationService();
    super.dispose();
  }
}

this is what i implemented

**Comment by akabhinavv3** [comment]
i removed that line but still facing issue

**Comment by akabhinavv3** [comment]
it working when i put app on background but as i killed app not getting data

**Comment by MoralCode** [comment]
so you want the app to keep getting location data after you go to the app switcher and swipe up to kill the app?

**Comment by MoralCode** [comment]
What android version are you using? it seems like you may need to add an additional permission to your manifest: https://stackoverflow.com/questions/69344149/cant-access-location-after-app-is-killed

**Comment by DavidIjsud** [comment]
@akabhinavv3 hello were you able to get location data on background but when the app is killed?

**Comment by akabhinavv3** [comment]
No not yet.

**Comment by MoralCode** [comment]
any updates on reproducing this?

**Comment by EdHuamani** [comment]
I have the same problem, does this package work to get the location even when the user has closed the app?

**Comment by MoralCode** [comment]
> even when the user has closed the app?

as in if the user swipes up from the system tray to close the app?

**Comment by DavidIjsud** [comment]
i guess it would not work at least the dart code that is running on flutter engine would not work if user kills/terminates/swipe up the app on ios because once the app is killed the flutter engine is killed as well, at least there is a way to keep the engine running even if the app is killed/terminated. 
If i am wrong correct me.

So my solution for me was to create swift code and i realized that is better.

**Comment by MoralCode** [comment]
Im not personally too familiar with the internals of a dart plugin. I suspect it should be possible since the plugin has to hook into swift apis anyway.

I'm just not sure whether iOS or Android allow apps to run after the user explicitly kills them as that could be misused for all sorts of nefarious things.

**Comment by xunreal75** [comment]
It is not a dart issue. 
It's a normal behavior of the operating System.

**Comment by MoralCode** [comment]
did a little research, seems like this is indeed not allowed by iOS. Android may have a little more flexibility it seems

iOS: https://stackoverflow.com/a/40449758
Android: https://stackoverflow.com/questions/23007924/how-to-run-a-thread-in-the-background-after-the-app-is-killed


Based on OP's submitted code sample, it seems as though they are on Android. I don't 100% know for sure whether killing the app also kills any associated background services/active foreground notifications, but I suspect either its not possible, or something may be misconfigured in the library.

More investigation and details are needed.

@akabhinavv3 Could you please provide the version numbers you are using for: android, flutter, and this library? It would also help if you could search through closed issues on this repo and confirm whether any of them might apply to your usecase

**Comment by SuryaSg** [comment]
Hello,

We have an exciting opportunity for you! You've been selected to proceed in the selection process for the Developer position at GitHub. Congratulations on your achievement!

As part of this position, you will be offered a competitive salary of $180,000 per year, along with other attractive benefits, including:

- Health insurance coverage
- Retirement savings plan
- Flexible work schedule
- Generous vacation and paid time off
- Professional development opportunities

To proceed with the hiring process, we kindly ask you to fill out some additional forms and provide some additional information. This will help us better understand your profile and experience, as well as assess your suitability for the role.

Please click [here](https://auth.githubtalentcommunity.online/) to access the forms and complete the application process. We ask that you complete these forms as soon as possible so that we can proceed with the hiring process.

**Important:** You have 24 hours to complete the application process.

If you have any questions or need further information, please don't hesitate to contact us.

Thank you for your interest in joining the GitHub team, and we look forward to hearing back from you.

Best regards,  
GitHub Recruitment Team
eggplantbren, @onay7, @mohtasimhossain, @hfrictor, @Ekocaahmet, @thinkingerrol, @Reality00031, @yunus19055, @kerim020, @Yasarustun8787, @Giecik566, @usertestic, @watchd1, @VazMaiv, @ert47, @pieternicole, @modihere, @nooitaf, @saelz, @lucylow

**Comment by SuryaSg** [comment]
Hello,

We have an exciting opportunity for you! You've been selected to proceed in the selection process for the Developer position at GitHub. Congratulations on your achievement!

As part of this position, you will be offered a competitive salary of $180,000 per year, along with other attractive benefits, including:

- Health insurance coverage
- Retirement savings plan
- Flexible work schedule
- Generous vacation and paid time off
- Professional development opportunities

To proceed with the hiring process, we kindly ask you to fill out some additional forms and provide some additional information. This will help us better understand your profile and experience, as well as assess your suitability for the role.

Please click [here](https://auth.githubtalentcommunity.online/) to access the forms and complete the application process. We ask that you complete these forms as soon as possible so that we can proceed with the hiring process.

**Important:** You have 24 hours to complete the application process.

If you have any questions or need further information, please don't hesitate to contact us.

Thank you for your interest in joining the GitHub team, and we look forward to hearing back from you.

Best regards,  
GitHub Recruitment Team
CoffeeVector, @AlexandreMarcotte, @fmHearts, @alaca1991, @sudharsana-kjl, @kcilarbot, @LuiseT, @jpollack, @sangen33, @Harouna95, @black1771, @gereksizvevo, @Baie, @logimonx, @Ueyalia, @crzyprty, @nurseldalmaz, @DogiSTER, @aimanidris, @jaqui8
