### ISSUE TITLE
SWIFT_VERSION Error

### ISSUE THREAD

**Issue by balinttakacs** [Almoullim/background_location#5]
> - `background_location` does not specify a Swift version and none of the targets (`Runner`) integrating it have the
>     `SWIFT_VERSION` attribute set. Please contact the author or set the `SWIFT_VERSION` attribute in at least one of the targets
>     that integrate this pod.

When i try run "flutter build ios" command, i get this error code.

**Comment by Almoullim** [comment]
I believe I must specify the minimum swift version in the library. But for the meantime, since I don't have much free time, adding a swift version to your project should fix this.

Check to see how you can do that [https://stackoverflow.com/questions/50458556/flutter-swift-version-must-be-set-to-a-supported-value](https://stackoverflow.com/questions/50458556/flutter-swift-version-must-be-set-to-a-supported-value)

**Comment by balinttakacs** [comment]
Thank you!

Now when i try Run a build from XCode, get this message: 
**"'background_location/background_location-Swift.h' file not found"**

**Comment by Almoullim** [comment]
@balinttakacs I believe this is because you haven't enabled swift in your project when you created it. if that's the case you can follow this answer https://stackoverflow.com/questions/54204418/make-flutter-project-swift-compatible-after-creation
