### ISSUE TITLE
Not Working in ios14

### ISSUE THREAD

**Issue by Hisagar** [Almoullim/background_location#51]
```dart
  void findLocation(int endTimeStamp) async {
    await BackgroundLocation.setNotificationTitle("Test Title");
    await BackgroundLocation.startLocationService();
    await BackgroundLocation.getLocationUpdates((location) async {
    	print(location.accuracy);
    });
  }
```

this is my code
working in android but not working in ios

**Comment by ozz-rjq** [comment]
can you please remove `await` before `BackgroundLocation.setNotificationTitle` and `BackgroundLocation.startLocationService()` and try again?

**Comment by Hisagar** [comment]
> can you please remove `await` before `BackgroundLocation.setNotificationTitle` and `BackgroundLocation.startLocationService()` and try again?

not working same issue!!

**Comment by Hisagar** [comment]
not even execute BackgroundLocation.setNotificationTitle("Test Title") this line. and then unable to execute startLocationService due to setNotificationTitle in ios but working android

**Comment by Almoullim** [comment]
firstly setNotificationTitle is for android only try removing that and then see if you get any errors and post them here. Thank you.

**Comment by jozes** [comment]
I have same problem - the app is not running on IOS14. I have commented the setNotificationTitle but that does not help. The app shows background usage of location services but the location is never displayed on the screen. Only the getCurrentLocation() prints the current location on the debugging output.
The same code runs ok on android.

**Comment by JankinHou** [comment]
Have you solved this problem?

**Comment by davidmokos** [comment]
Happening to me as well on iOS 14.3 and latest backbround_location version 0.3.0.

**Comment by phanbaohuy96** [comment]
@JankinHou  @davidmokos i have the same issues but it's okay when trying to rearrange the method that :
#Before
```
await BackgroundLocation.startLocationService();

BackgroundLocation.getLocationUpdates((location) {
   ...
});
```

#After
```
BackgroundLocation.getLocationUpdates((location) {
   ...
});

await BackgroundLocation.startLocationService();
```
Could you guys try to resolve this issue?

**Comment by FabioXimenes** [comment]
I am having the same issue. It's working in android, but not in ios. Someone have solved it? @phanbaohuy96 I tried your suggestion, but it's not working.

Flutter version: 1.22.6

**Comment by jozes** [comment]
Hi all!

The solution that works perfectly for me  is to start the service without "await". So it looks like the example program is somehow wrong, at least for the IOS platform.

This is the code I use in my application to start the background service. It works perfectly, I get the blue bar on top of the screen when app is running in the background and I hope that there will be a switch available to make  this bar visible or not visible in the future. This works both with version 0.4.0 and 0.4.1. So far I had not a single issue with this solution.
So to start the background location service i use the following code. You can just skip the line which reads the preference and pass a double parameter directly as distance filter.

if (Platform.isIOS) {
      _distanceFilter = int.tryParse(PrefService.getString('distanceFilter'));
      BackgroundLocation.startLocationService(
          distanceFilter: _distanceFilter.toDouble());
      BackgroundLocation.getLocationUpdates((location) {
        onNewLocation(location);
      });
}

void onNewLocation(Location _location) async {
 // process the location according to your needs. In my case I insert it into SQFlite database.
}

To stop the background service:
    
if (Platform.isIOS) {
      BackgroundLocation.stopLocationService();
}

So far this package is the best possible solution I have found for background location gathering on IOS, simple and efficient. For android I have added some code so that the service survives also pressing the back button. I am planning to publish that as well. For those, who would like to play with the code, see the solution at https://github.com/ppicas/flutter-android-background, which works perfectly only on android and which I used as a base for my improvement which is now being tested.

**Comment by jozes** [comment]
@Almoullim So far this is the best solution I found and covers all of my needs. It would be great if you could update the example program and use the platform checks before starting the the service. That would make less confusion among users and the example program would run right away without any needs for debugging on IOS platform . I am looking forward to see the next version of the package with further functionality.

@Hisagar  @Almoullim I  think you can mark this thread as closed.
