### ISSUE TITLE
Problem while updating project dependencies due to version conflicts of permission handler plugin used by plugin and project

### ISSUE THREAD

**Issue by vaimikpatel2908** [Almoullim/background_location#83]
background_location plugin depends on the permission handler 5.0.1+1 version and my other plugin needs to be updated which triggers the conflict with the permission handler version's plugin_platform_interface version. Therefore, I updated the permission handler plugin version. Now, It shows conflict with the background location plugin version as it still depends on the older version of the permission handler plugin version. Is there any kind of work going on regarding this issue? or I have to move on with another plugin to resolve this issue.

**Comment by IshanDhruv** [comment]
The conflict of background_location v0.4.1 with firebase_core v1.0.1: Because no versions of background_location match >0.4.1 <0.5.0 and background_location 0.4.1 depends on permission_handler ^5.0.1+1, background_location ^0.4.1 requires permission_handler ^5.0.1+1.


And because permission_handler >=5.0.1 <=5.0.1+1 depends on permission_handler_platform_interface ^2.0.1 and permission_handler ^5.1.0 depends on permission_handler_platform_interface ^2.0.2, background_location ^0.4.1 requires permission_handler_platform_interface ^2.0.1 or permission_handler >=5.0.1+2 <5.1.0.
And because permission_handler >=5.0.1+2 <5.1.0 depends on permission_handler_platform_interface 2.0.1 which depends on plugin_platform_interface ^1.0.2, background_location ^0.4.1 requires plugin_platform_interface ^1.0.2.


And because firebase_core >=1.0.0 depends on firebase_core_platform_interface ^4.0.0 which depends on plugin_platform_interface ^2.0.0, background_location ^0.4.1 is incompatible with firebase_core >=1.0.0.
So, because accident_identifier depends on both firebase_core ^1.0.1 and background_location ^0.4.1, version solving failed.
pub get failed (1; So, because accident_identifier depends on both firebase_core ^1.0.1 and background_location ^0.4.1, version solving failed.)

**Comment by sisalik1** [comment]
Any fixes?

_Because background_location >=0.1.2 depends on permission_handler ^5.0.1+1 and MY_APP depends on permission_handler ^6.1.1, background_location >=0.1.2 is forbidden.
So, because MY_APP depends on background_location ^0.4.1, version solving failed._

**Comment by curciel** [comment]
Looking at the pubspeck it seems that its updated the yaml but not the .lock

**Comment by IshanDhruv** [comment]
This issue has been fixed in #78

**Comment by vaimikpatel2908** [comment]
Yes, the issue has been fixed, but not released in a stable version of the plugin for real-time application usage. It is just merged to the master branch at this moment.

**Comment by IshanDhruv** [comment]
Yup, at the moment you're going to have to link to the master branch until the package is updated.

**Comment by Almoullim** [comment]
Its done, sorry for the delay @IshanDhruv @vaimikpatel2908
